### ISSUE TITLE
RETRY_DELAY_MIN  RETRY_COUNT

### ISSUE THREAD

**Issue by bucolo** [kaloskagatos/EDF-Tempo-E-Ink-Display#4]
Bonjour, j'utilise la version avec le preview RTE. 
sur home assistant avec le module RTE tempo  j'ai remarqué que la couleur du lendemain "arrivait" souvent entre 6h30 et 6h40 , des fois un peu avant , des fois un peu après.
j'ai donc modifié l'heure de réveil à 6h30 , reglé  RETRY_DELAY_MIN = 5 et RETRY_COUNT = 7 pour avoir des essais de 6h30 a 7h05 .
Mais hélas ca n'a pas l'air de fonctionner, ce matin la couleur rouge est arrivé à 6h32 et a 6h46 l'esp m'affichait toujours ??? .
Et à 6h45 je n'ai pas vu de réveil de l'esp.
j'ai fais un reset juste après le rouge s'est bien affiché.
J'ai sans doute  zappé un truc dans le fonctionnement des retry , merci de m’éclairer.

**Comment by LArtisanDuDev** [comment]
Je n'ai pas géré le retry sur l'API RTE.
Il faudrait rajouter un booleen du genre isRTEFound et adapter le test de la ligne
https://github.com/LArtisanDuDev/EDF-Tempo-E-Ink-Display/blob/main/eTempo/eTempo.ino#L557
La subtilité c'est que le retry sur l'API RTE n'est pas nécessaire à minuit et à 11h...

**Comment by LArtisanDuDev** [comment]
Qq petites corrections réalisées, ça devrait être ok ici : https://github.com/LArtisanDuDev/EDF-Tempo-E-Ink-Display/tree/platformio

**Comment by bucolo** [comment]
Super , merci, je viens de faire l'update (en gardant Arduino IDE) . On verra demain ou apres demain ce que ca donne.
Merci encore
ps: pour info j'ai testé, sur un autre lilygo T5, un ecran e-ink blanc noir rouge en remplacement de l’écran d'origine defectueux (le brochage est compatible).
ca marche mais le rafraichissement d'ecran est long. Il faut prendre la bibliothèque GxEPD2.
![image](https://github.com/kaloskagatos/EDF-Tempo-E-Ink-Display/assets/121181184/4c2df1af-6827-4f3a-bbce-2a3dad355726)
Pour tester j'ai fais comme ci le bleu était rouge ...

**Comment by LArtisanDuDev** [comment]
Désolé, mais je n'ai mis en place les évolutions que sur la branche platformio (qui compile environ 10 fois plus vite). Je n'ai pas mis à jour la branche main qui est pour Arduino IDE. Vu le compte de jours vous avez sur votre photo vous devez avoir l'ancienne version.

**Comment by LArtisanDuDev** [comment]
https://github.com/LArtisanDuDev/EDF-Tempo-E-Ink-Display/tree/main à jour (Arduino IDE)

**Comment by bucolo** [comment]
Merci c'etait bon, j'avais bien renommé le cpp en ino . C'est juste que pour la version "couleur" j'avais commencé les modifs depuis une ancienne version.
Sinon j 'ai remarqué que le triangle s'affiche a 00:05 alors qu'a cette heure c'est normal.
J'ai pu modifié ça . J'ai remis aussi le jours restant plutôt que les jours écoulé (ma femme préfère) mais en supprimant le /300  /43 /22 ce qui me permet de liberer de la place et d'afficher l'heure du prochain réveil.  
![image](https://github.com/kaloskagatos/EDF-Tempo-E-Ink-Display/assets/121181184/d8ff75bc-6630-4c38-b870-aee5728d4f63)
le boitier à imprimer : https://www.thingiverse.com/thing:4055993

**Comment by LArtisanDuDev** [comment]
Nos MOA décident de tout :)
Le boitier peut être facilement rendu plus profond ? ma batterie est une 18650 qui est un peu épaisse...

**Comment by bucolo** [comment]
Plus épaisse et un peu plus large a priori.
Il y a quelques boitier pour T5 2.13 sur thingverse mais aucun n'a l'air d'aller.
Si tu me donnes les dimensions de ton support de 18650 mon fils devrait pouvoir recréer un stl  à partir de celui que j'ai utilisé .

**Comment by bucolo** [comment]
Mes modifs concernant le retry pour la couleur du lendemain n'etait pas suffisante.
Contrairement a ce que l'on pourrait penser il faut indiquer : 

// Tableau des heures de réveil
const WakeupTime wakeupTimes[] = {
  {0, 5, false},  // Réveil à 00:05
  {6, 30, _**false**_},  // Réveil à 06:30 pour préview RTE
  {11, 5, true}  // Réveil à 11:05
}; 

pour ne pas avoir de retry a 00:05

**Comment by kaloskagatos** [comment]
Bonjour, j'ai mis à jour la branche principale, j'ai changé toute l'architecture donc il faudra recréer un ticket si un nouveau problème apparaît. 
Lire le README section Arduino IDE pour le réglage de l'IDE en cas d'erreur de compilation.
