### ISSUE TITLE
Plus de récupération du jour tempo

### ISSUE THREAD

**Issue by rempal** [kaloskagatos/EDF-Tempo-E-Ink-Display#6]
Depuis plusieurs semaine, la récupération des jours tempo semblent ne plus fonctionner. Le jour J et J+1 indique "N/A" et le décompte des jours indique "???".
Piste de debug : l'url de récupération des informations semble ne plus fonctionner.

**Comment by LArtisanDuDev** [comment]
Effectivement, les api EDF ne fonctionnent plus.

**Comment by kaloskagatos** [comment]
Il y a une solution facile avec l'API https://www.api-couleur-tempo.fr/api

Sinon il faudra utiliser l'API RTE mais ça nécessite de créer un compte ce qui est moins pratique pour tout le monde.

J'attends qu'il fasse plus froid pour m'y remettre ;)

**Comment by TrimVa** [comment]
> Il y a une solution facile avec l'API https://www.api-couleur-tempo.fr/api
> 
> Sinon il faudra utiliser l'API RTE mais ça nécessite de créer un compte ce qui est moins pratique pour tout le monde.
> 
> J'attends qu'il fasse plus froid pour m'y remettre ;)

Top merci, j'avais peur que le projet soit mort 👌

**Comment by nicolas2k** [comment]
c'est dommage qu'on n'a plus le jour restant de chaque couleur ... Je n'ai toujours pas trouvé.

**Comment by LArtisanDuDev** [comment]
> c'est dommage qu'on n'a plus le jour restant de chaque couleur ... Je n'ai toujours pas trouvé.

Vous pouvez aller faire un tour dans mes repos, j'ai codé ça.

**Comment by kaloskagatos** [comment]
Bonjour, j'ai mis à jour la branche principale, ça fonctionne de nouveau. Lire le README section Arduino IDE pour le réglage de l'IDE en cas d'erreur de compilation.

**Comment by kaloskagatos** [comment]
Fixed

**Comment by rempal** [comment]
Super !! Merci pour le travail !!
